<MyRoot>:
    random_label: random_label
    BoxLayout:
        orientation:'vertical'
        Label:
            text:'RandomRumber'
            font_size: 64
            color: 0.92 , 0.45 , 0 , 1 #normalized valuse
        Label:
            id: random_label
            text: '-'
            font_size: 64
        Button:
            text: 'Gen'
            font_size: 32
            on_press: root.RandomPress()